Month 8/step 1
Jaki1965/react-stellar-burger pull request #3
Opened 2023-05-25 12:08 UTC by Jaki1965

Сдаю проект Month 8/step 1 на первое ревью (commit 45)

2023-05-25 12:27 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- хорошо разобрались в контексте
- в контекст обернуты только те компоненты, которые должны его использовать
- нет лишнего кода

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- передавайте данные в список ингредиентов так же через контекст
- поправьте propTypes у конструктора 

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-25 12:27 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            {stateData.length && <BurgerIngredients data={stateData} />}
**можно лучше**
Если вы данные передаёте через контекст, то не нужно их тут передавать как пропсы

2023-05-25 12:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +      .catch((err) => {console.log(err)})
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-05-25 12:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +
**необходимо исправить**
Вы больше не принимаете data через пропсы, поэтому смысла в propTypes нет

2023-05-25 18:45 UTC, Jaki1965 commented
Устранены замечания ревьюера. Отправляю на ревью 2 проекта - month-8/step-1 (commit 48)

2023-05-25 19:51 UTC, Jaki1965 commented
Обнаружил лишние закоментирванные строки - устранил. (commit 49)

2023-05-25 22:08 UTC, Jaki1965 commented
Убрал "мертвые" импорты. (commit 50)

2023-05-26 07:00 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

**Можно лучше**
Папку `build`  стоит добавить в `gitignore` - она на гитхабе не нужна.

2023-06-20 06:02 UTC, merged