Month 8/step 2
Jaki1965/react-stellar-burger pull request #4
Opened 2023-06-03 22:14 UTC by Jaki1965

Отправляю проект month-8/step-2 на первое ревью

2023-06-04 03:26 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редьюсеры - чистые функции
- Правильно настроен `Dnd` 
- Хорошая организация хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В массив айдишников запроса на оформление заказа попадают не те ингредиенты, которые были добавлены в конструктор. 

<img width="1427" alt="Снимок экрана 2023-06-04 в 06 20 08" src="https://github.com/Jaki1965/react-stellar-burger/assets/60173362/8a197ec8-466d-4b07-8a12-80b1d05a0934">

- разделите редьюсер на несколько 

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-04 03:26 UTC, andryxxa93 commented on src/components/services/main-context.jsx
> +export const OrderContext = React.createContext();
**Можно лучше**
Контекст больше не нужен - его можно удалить

2023-06-04 03:26 UTC, andryxxa93 commented on src/components/services/reducers/api.js
> +import {
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-06-04 03:26 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const {data} = useSelector(store => store.data);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-06-04 13:01 UTC, Jaki1965 commented
* Устранено замечание ревьюера - "В массив айдишников запроса на оформление заказа попадают не те ингредиенты, которые были добавлены в конструктор". Перенаправлен запрос на получение данных с сервера. Изменена переменная orderIngridients в BurgerConstructor, являющаяся аргументом запроса заказа
  
  const allElements = ingredients.map(element => element);
  if(buns!==null){allElements.push(buns)};
  
  const orderIngridients = React.useMemo(() => allElements.map((i) => {if(allElements.length){return i._id}
    }), [allElements]);
    
    (commit 82)
* Устранено замечание ревьюера - "Контекст больше не нужен - его можно удалить". Удалено (commit 83)
* Устранено замечание ревьюера - "со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например:

загрузка данных ингредиентов
отправка заказа
работа конструктора
открытие модального окна ингредиента".

Редъюсеры разделены и собраны в src/components/srvices/reducers/index.js

import { combineReducers } from 'redux';
import { getDataReducer} from './data-reducer';
import { getOrderReducer} from './order-reducer';
import { itemReducer} from './item-reducer';
import { ingredientMoveReducer} from './burger-constructor';
import { madalReducer} from './modal-reducer';

export const rootReducer = combineReducers({
  data: getDataReducer,  // запрос данных ингредиентов с сервера
  order: getOrderReducer, // запоос заказа с сервера
  item: itemReducer, // открытие модального окна с ингредиентом
  open: madalReducer, // открытие модального окана с заказом
  ingredients: ingredientMoveReducer, // работа конструктора: перемещение инградиента в конструктор, сортировка инградиентов в конструкторе

});

});
(commit 84)
* Созданы раздельные директории под разные редьюсеры (commit 85)

2023-06-05 07:53 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-20 06:01 UTC, Jaki1965 commented
Merge branch to main

2023-06-20 06:02 UTC, merged